import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    globalSetup: ['./tests/steps/init.mjs'], //  run before all the tests are run. Which, in our case, sets up the environment variables by loading the content of the .env file generated by the serverless-export-env plugin.
    include: ['**/*.test.mjs'],
    exclude: ['**/node_modules/**', '**/dist/**'],
    environment: 'node',
  },
});
